apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: busybox:1.28
    name: demo-pod
    securityContext:
      privileged: true
    command: [ "sh", "-c", "sleep 1h" ]

