apiVersion: v1
kind: Pod
metadata:
  name: super-secret
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx
    name: demo-pod
  nodeSelector:
    kubernetes.io/hostname: worker2

